---
collections:
  - name: ansible.posix
    version: 2.0.0
  - name: ansible.utils
    version: 5.1.2
  - name: community.general
    version: 10.7.2
  - name: community.sops
    version: 2.0.3
  - name: kubernetes.core
    version: 5.4.1
roles:
  - name: xanmanning.k3s
    version: v3.4.4
