# https://external-secrets.io/latest/provider/fake/
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
    name: fake
    namespace: kube-system
spec:
    provider:
        fake:
            data:
                - key: /databases/postgres/username
                  value: postgres_user
                  version: v1
                - key: /databases/postgres/password
                  value: 2Zh9DtHl$JhDDyIuzY85yfyz-
                  version: v1
                - key: /databases/postgres/init_postgres_super_pass
                  value: Ysbl01iFT!jitaD3Yyl5RBq0nD
                  version: v1
                - key: /databases/postgres/placeholder
                  value: vnAYUkeJJgdMw!YrEbStF.79zHv!7sFtpomgrZaLYyQ5HAsQQ7e
                  version: v1
                - key: /dummy/map
                  valueMap:
                    foo: example
                    other: thing
                - key: /best/use/case/vault
                  valueMap:
                    # Users resources are managed here by themself
                    users: /<scope>/users/<username>/<resource>/<subresource>/<version>
                    # I developed this
                    apps: /<scope>/apps/<system>/<env>/<version>
                    # Some other guy developed this
                    services: /<scope>/services/<system>/<env>/<version>
                  version: v1
                - key: /global/services/postgres/dev
                  version: v1
                  valueMap:
                    username: postgres_user
                    password: ESNYKrH5vw!YrEbStF.79zHv!7sFtpomgrZaLmnXmwt!Fhh.vEo.CTLiMR3CTDJ
                    init_postgres_super_pass: vnAYUkvw!YrEbStF.7eJJgdMw!YrEbmnXmwt!Fhh.vEo.CTLiMRStF.79z
                - key: /global/services/wireguard/dev
                  version: v1
                  valueMap:
                    private_key: mMWpKTEOO97srapoC6rMQJUnDq+RDRjZez7X2KWdm0I=
                    preshared_key: Aj8YUVkyJeBPbiDTD+hqMzvnxS/i/Ye2ZkcUnd4cjTk=
                    public_key: oY87nclwm7SNJMzJsULPS6Qjrx9Gm61eS3t0nV/ywyQ=
                    endpoint_ip: 144.91.73.225
                    addresses: 10.13.13.3/32
                - key: /global/users/daniel/ssh/home
                  version: v1
                  valueMap:
                    ssh_key: key
                - key: /global/users/daniel/sites/blog
                  value: value
                  version: v1
